# Financial Integrations Configuration
# Secure API connections and data synchronization with financial platforms

# Personal Finance Management Tools
financial_tools:
  mint:
    enabled: true
    provider: "Intuit Mint"
    connection_type: "oauth2"
    api_version: "v1"
    credentials:
      client_id: "encrypted:mint_client_id_hash"
      client_secret: "encrypted:mint_client_secret_hash"
      access_token: "encrypted:mint_access_token_hash"
      refresh_token: "encrypted:mint_refresh_token_hash"
    sync_frequency: "daily"
    sync_time: "06:00"  # UTC
    data_types:
      - "transactions"
      - "balances"
      - "budgets"
      - "credit_score"
    rate_limits:
      requests_per_hour: 100
      requests_per_day: 1000
    status: "active"
    last_sync: "2024-09-20T06:00:00Z"
    sync_errors: 0

  ynab:
    enabled: false
    provider: "You Need A Budget"
    connection_type: "api_key"
    api_version: "v1"
    credentials:
      api_key: "encrypted:ynab_api_key_hash"
    sync_frequency: "daily"
    data_types:
      - "budgets"
      - "transactions"
      - "categories"
    status: "disabled"
    notes: "Disabled in favor of Mint integration"

  personal_capital:
    enabled: true
    provider: "Personal Capital"
    connection_type: "screen_scraping"
    credentials:
      username: "encrypted:pc_username_hash"
      password: "encrypted:pc_password_hash"
    sync_frequency: "weekly"
    sync_day: "sunday"
    data_types:
      - "investment_holdings"
      - "net_worth_tracking"
      - "fee_analysis"
    status: "active"
    two_factor_setup: true

# Banking APIs and Connections
bank_apis:
  plaid:
    enabled: true
    provider: "Plaid"
    api_version: "2020-09-14"
    environment: "production"  # sandbox, development, production
    credentials:
      client_id: "encrypted:plaid_client_id_hash"
      secret: "encrypted:plaid_secret_hash"
      public_key: "encrypted:plaid_public_key_hash"
    connected_institutions:
      - institution_name: "Chase"
        institution_id: "ins_109508"
        accounts:
          - "Primary Checking"
          - "Business Checking"
        connection_status: "active"
        last_sync: "2024-09-20T08:00:00Z"
      - institution_name: "Marcus by Goldman Sachs"
        institution_id: "ins_109512"
        accounts:
          - "Emergency Fund"
        connection_status: "active"
        last_sync: "2024-09-20T08:00:00Z"
    sync_frequency: "daily"
    webhooks:
      enabled: true
      endpoint: "https://your-app.com/webhooks/plaid"
      events:
        - "TRANSACTIONS"
        - "ACCOUNTS"
        - "ITEM"

  chase_api:
    enabled: true
    provider: "JPMorgan Chase"
    connection_type: "direct_api"
    api_version: "v2"
    credentials:
      api_key: "encrypted:chase_api_key_hash"
      api_secret: "encrypted:chase_api_secret_hash"
    connected_accounts:
      - "checking"
      - "savings"
      - "credit_card"
    sync_frequency: "real_time"
    features:
      - "balance_inquiry"
      - "transaction_history"
      - "payment_initiation"
    status: "active"

  ally_bank:
    enabled: true
    provider: "Ally Bank"
    connection_type: "oauth2"
    credentials:
      client_id: "encrypted:ally_client_id_hash"
      client_secret: "encrypted:ally_client_secret_hash"
    connected_accounts:
      - "House Down Payment"
    sync_frequency: "daily"
    status: "active"

# Investment Platform Integrations
investment_platforms:
  fidelity:
    enabled: true
    provider: "Fidelity Investments"
    connection_type: "manual_upload"  # No API available
    data_sources:
      - "monthly_statements"
      - "quarterly_reports"
      - "transaction_exports"
    upload_schedule: "monthly"
    data_types:
      - "balances"
      - "transactions"
      - "performance"
      - "holdings"
    last_update: "2024-09-15T12:00:00Z"
    automation_level: "semi_automated"  # Manual download, automated processing

  vanguard:
    enabled: true
    provider: "Vanguard"
    connection_type: "personal_api"
    credentials:
      username: "encrypted:vanguard_username_hash"
      password: "encrypted:vanguard_password_hash"
    accounts:
      - "Roth IRA"
    sync_frequency: "daily"
    data_types:
      - "account_balances"
      - "holdings"
      - "transactions"
      - "performance_data"
    status: "active"
    two_factor_enabled: true

  schwab:
    enabled: true
    provider: "Charles Schwab"
    connection_type: "api_v2"
    credentials:
      app_key: "encrypted:schwab_app_key_hash"
      app_secret: "encrypted:schwab_app_secret_hash"
      access_token: "encrypted:schwab_access_token_hash"
    accounts:
      - "individual_investment"
    sync_frequency: "daily"
    data_types:
      - "positions"
      - "transactions"
      - "market_data"
      - "account_info"
    status: "active"

# Business and Tax Tools
business_tools:
  quickbooks:
    enabled: true
    provider: "Intuit QuickBooks Online"
    connection_type: "oauth2"
    api_version: "v3"
    credentials:
      client_id: "encrypted:qb_client_id_hash"
      client_secret: "encrypted:qb_client_secret_hash"
      access_token: "encrypted:qb_access_token_hash"
      refresh_token: "encrypted:qb_refresh_token_hash"
      company_id: "encrypted:qb_company_id_hash"
    sync_frequency: "weekly"
    sync_day: "sunday"
    data_types:
      - "income"
      - "expenses"
      - "tax_categories"
      - "profit_loss"
    status: "active"

  turbotax:
    enabled: true
    provider: "Intuit TurboTax"
    connection_type: "manual_import"
    data_sources:
      - "annual_tax_returns"
      - "estimated_payments"
      - "deduction_tracking"
    sync_frequency: "annual"
    last_update: "2024-04-15T00:00:00Z"

# Credit Monitoring and Reporting
credit_monitoring:
  credit_karma:
    enabled: true
    provider: "Credit Karma"
    connection_type: "oauth2"
    credentials:
      username: "encrypted:ck_username_hash"
      password: "encrypted:ck_password_hash"
    data_types:
      - "credit_scores"
      - "credit_reports"
      - "recommendations"
    sync_frequency: "weekly"
    status: "active"

  experian:
    enabled: true
    provider: "Experian"
    connection_type: "api_v1"
    credentials:
      api_key: "encrypted:experian_api_key_hash"
      subscription_id: "encrypted:experian_sub_id_hash"
    data_types:
      - "fico_score"
      - "credit_monitoring"
      - "identity_monitoring"
    sync_frequency: "daily"
    status: "active"

# Real Estate and Property
real_estate:
  zillow:
    enabled: true
    provider: "Zillow"
    connection_type: "api_v1"
    credentials:
      api_key: "encrypted:zillow_api_key_hash"
    data_types:
      - "property_values"
      - "market_trends"
      - "rental_estimates"
    sync_frequency: "monthly"
    status: "active"

  redfin:
    enabled: false
    provider: "Redfin"
    connection_type: "web_scraping"
    status: "disabled"
    notes: "Disabled due to rate limiting issues"

# Integration Security and Management
security:
  encryption:
    algorithm: "AES-256-GCM"
    key_management: "aws_kms"  # or "azure_key_vault", "hashicorp_vault"
    key_rotation_schedule: "quarterly"
    last_key_rotation: "2024-07-01T00:00:00Z"

  access_control:
    multi_factor_authentication: true
    session_timeout_minutes: 30
    ip_whitelist:
      - "192.168.1.0/24"  # Home network
      - "10.0.0.0/8"      # Office network
    api_rate_limiting: true

  monitoring:
    failed_login_threshold: 3
    suspicious_activity_detection: true
    audit_logging: true
    alert_notifications:
      email: "security-alerts@yourdomain.com"
      sms: "+1234567890"

  compliance:
    pci_dss_compliant: true
    sox_compliant: true
    gdpr_compliant: true
    data_retention_policy: "7_years"

# Sync Configuration and Status
sync_management:
  global_settings:
    sync_enabled: true
    sync_window_start: "05:00"  # UTC
    sync_window_end: "07:00"    # UTC
    max_retry_attempts: 3
    retry_backoff_multiplier: 2
    timeout_seconds: 30

  error_handling:
    continue_on_error: true
    error_notification_threshold: 3
    automatic_retry: true
    fallback_to_manual: true

  performance:
    batch_size: 100
    concurrent_connections: 5
    cache_enabled: true
    cache_ttl_hours: 1

# Status Dashboard
status:
  overall_health: "healthy"  # healthy, degraded, critical
  active_connections: 12
  failed_connections: 0
  last_full_sync: "2024-09-20T06:00:00Z"
  next_scheduled_sync: "2024-09-21T06:00:00Z"

  uptime_stats:
    current_month: "99.8%"
    last_month: "99.9%"
    year_to_date: "99.7%"

  data_freshness:
    real_time_accounts: 6     # Updated continuously
    daily_sync_accounts: 4    # Updated once per day
    weekly_sync_accounts: 2   # Updated weekly
    manual_accounts: 2        # Require manual updates